on:
  push:
    branches: [main]
  pull_request:
name: CI
jobs:
  flatpak-builder:
    name: "Flatpak Builder"
    runs-on: ubuntu-20.04
    container:
      image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/rust_bundle:master
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions@v2
      with:
        bundle: "qrscanner.flatpak"
        manifest-path: "com.belmoussaoui.qrscanner.Devel.json"
        run-tests: "true"
